import { useState } from 'react';
import {
  BookOpen,
  Shield,
  ArrowRight,
  Sparkles,
  School,
  CheckCircle,
  ChevronDown,
  BarChart,
  FileText,
  HeartHandshake
} from 'lucide-react';

interface LandingPageProps {
  onNavigate: (route: string) => void;
}

export default function LandingPage({ onNavigate }: LandingPageProps) {
  const [activeFAQ, setActiveFAQ] = useState<number | null>(null);

  const handleSelectPortal = (route: string) => {
    window.history.pushState({}, '', route);
    onNavigate(route);
  };

  const toggleFAQ = (index: number) => {
    setActiveFAQ(activeFAQ === index ? null : index);
  };

  const stats = [
    { value: '25,000+', label: 'Active learners', sub: 'Across UK & Egypt' },
    { value: '98.4%', label: 'Parent satisfaction', sub: 'Based on 2026 surveys' },
    { value: '100%', label: 'Certified tutors', sub: 'Vetted & DBS-checked' },
    { value: 'Ofsted', label: 'Framework aligned', sub: 'Standards compliant' },
  ];

  const features = [
    {
      number: '01',
      category: 'Curriculum',
      icon: <FileText size={16} />,
      color: 'green',
      title: '39-week structured scheme',
      description:
        'A complete, day-by-day learning plan aligned strictly with the British National Curriculum from Reception through Year 11.',
    },
    {
      number: '02',
      category: 'AI',
      icon: <Sparkles size={16} />,
      color: 'amber',
      title: 'AI-powered learning companion',
      description:
        'Instant tailored study notes, practice questions, and diagnostic gap analysis generated by a safe, sandbox-bound AI tutor.',
    },
    {
      number: '03',
      category: 'Analytics',
      icon: <BarChart size={16} />,
      color: 'blue',
      title: 'In-depth parent analytics',
      description:
        'Track lessons completed, attendance, work portfolios, and progress reports. Export evidence portfolios with a single click.',
    },
    {
      number: '04',
      category: 'Safeguarding',
      icon: <Shield size={16} />,
      color: 'red',
      title: 'Daily safeguarding checks',
      description:
        'Pupil wellbeing check-ins, a secure concern log, and direct safety pathways — designed by UK safeguarding officers.',
    },
  ];



  const faqs = [
    {
      question: 'What is the difference between the Homeschooling and Tuition portals?',
      answer:
        'The Homeschooling portal is a complete, full-time solution for parents directing their child\'s education — full curriculum schemes, grading logs, and parent portfolios. The Tuition portal is for supplementary learning, connecting students with certified tutors for live sessions, assignments, and targeted subject support.',
    },
    {
      question: 'Are the study programmes aligned with the British Curriculum?',
      answer:
        'Yes. Both portals strictly adhere to UK National Curriculum guidelines, covering Key Stage 1 through Key Stage 4 (GCSE preparation). Students in Egypt can follow the same curriculum standards as UK-based learners.',
    },
    {
      question: 'How does the safeguarding system work?',
      answer:
        'Our platform includes daily wellbeing check-ins for students, a secure Concern Log for parents and teachers, and immediate access to dedicated support helplines. Safeguarding officers are notified instantly of high-severity concern logs.',
    },
    {
      question: 'Can I register multiple children?',
      answer:
        'Absolutely. Parents can add and manage profiles for multiple children from a single dashboard, customising year groups and subjects for each child independently.',
    },
  ];

  const featureColorMap: Record<string, { bg: string; icon: string }> = {
    green: { bg: '#f1f3ee', icon: '#506e4d' }, // Warm Sage Green highlight
    amber: { bg: '#faf7f0', icon: '#c06d48' }, // Soft Terracotta highlight
    blue: { bg: '#e8edf8', icon: '#1a3566' },
    red:   { bg: '#fce8e8', icon: '#a03030' },
  };

  return (
    <>
      <style>{`
        /* ── Reset & base ── */
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        .ilm-page { font-family: 'Inter', system-ui, sans-serif; background: #f7f5ef; color: #2b352a; line-height: 1.6; overflow-x: hidden; }

        /* ── NAV ── */
        .ilm-nav {
          display: flex; align-items: center; justify-content: space-between;
          padding: 0.9rem 2.5rem; background: #fff;
          border-bottom: 1px solid #dfdacd; position: sticky; top: 0; z-index: 100;
        }
        .ilm-nav-logo { display: flex; align-items: center; gap: 10px; }
        .ilm-logo-mark {
          width: 36px; height: 36px; background: #506e4d; border-radius: 8px;
          display: flex; align-items: center; justify-content: center;
        }
        .ilm-logo-mark svg { color: #fff; }
        .ilm-brand-name { font-size: 17px; font-weight: 700; letter-spacing: 0.07em; color: #2b352a; display: block; }
        .ilm-brand-tag  { font-size: 10px; font-weight: 400; letter-spacing: 0.13em; color: #506e4d; text-transform: uppercase; display: block; }
        .ilm-nav-links  { display: flex; gap: 1.75rem; list-style: none; }
        .ilm-nav-links a { font-size: 13px; color: #5a6557; text-decoration: none; letter-spacing: 0.01em; transition: color 0.15s; }
        .ilm-nav-links a:hover { color: #506e4d; }
        .ilm-nav-badge {
          display: flex; align-items: center; gap: 6px; font-size: 11px;
          background: #f0ede4; color: #506e4d; padding: 5px 13px;
          border-radius: 20px; border: 1px solid #dfdacd; letter-spacing: 0.03em;
        }
        .ilm-nav-badge svg { color: #506e4d; }

        /* ── HERO ── */
        .ilm-hero { padding: 5rem 2rem 4rem; text-align: center; max-width: 860px; margin: 0 auto; }
        .ilm-eyebrow {
          display: inline-flex; align-items: center; gap: 8px;
          font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase;
          color: #506e4d; background: #f0ede4; border: 1px solid #dfdacd;
          padding: 5px 14px; border-radius: 20px; margin-bottom: 1.75rem; font-weight: 500;
        }
        .ilm-eyebrow svg { color: #506e4d; }
        .ilm-hero h1 {
          font-size: clamp(30px, 5vw, 52px); font-weight: 700; line-height: 1.12;
          color: #2b352a; letter-spacing: -0.02em; margin-bottom: 1.25rem;
        }
        .ilm-hero h1 .h1-accent { color: #506e4d; }
        .ilm-hero h1 .h1-underline { position: relative; display: inline-block; }
        .ilm-hero h1 .h1-underline::after {
          content: ''; position: absolute; left: 0; bottom: -2px;
          width: 100%; height: 3px; background: #dfdacd; border-radius: 2px;
        }
        .ilm-hero-sub {
          font-size: 16px; color: #5a6557; max-width: 540px;
          margin: 0 auto 2rem; line-height: 1.75;
        }
        .ilm-hero-ctas { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }

        /* ── BUTTONS ── */
        .ilm-btn-primary {
          background: #506e4d; color: #fff; padding: 13px 26px; border-radius: 8px;
          font-size: 14px; font-weight: 500; border: none; cursor: pointer;
          display: inline-flex; align-items: center; gap: 8px; letter-spacing: 0.01em;
          transition: background 0.15s; text-decoration: none;
        }
        .ilm-btn-primary:hover { background: #415a3e; }
        .ilm-btn-primary svg  { color: #fff; }
        .ilm-btn-secondary {
          background: #fff; color: #506e4d; padding: 13px 26px; border-radius: 8px;
          font-size: 14px; font-weight: 500; border: 1.5px solid #dfdacd;
          cursor: pointer; letter-spacing: 0.01em; transition: background 0.15s;
          text-decoration: none; display: inline-flex; align-items: center;
        }
        .ilm-btn-secondary:hover { background: #f7f5ef; }

        /* ── SECTION SHARED ── */
        .ilm-section       { padding: 4.5rem 2rem; }
        .ilm-container     { max-width: 920px; margin: 0 auto; }
        .ilm-section-label { font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase; color: #506e4d; font-weight: 500; margin-bottom: 0.4rem; }
        .ilm-section-title { font-size: clamp(22px, 3vw, 32px); font-weight: 700; color: #2b352a; letter-spacing: -0.015em; line-height: 1.22; margin-bottom: 0.6rem; }
        .ilm-section-desc  { font-size: 15px; color: #5a6557; max-width: 520px; line-height: 1.7; }
        .ilm-section-hdr   { margin-bottom: 2.5rem; }

        /* ── PORTALS ── */
        .ilm-portals-bg { background: #f7f5ef; }
        .ilm-portals-list {
          display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem;
          max-width: 1000px; margin: 0 auto;
        }
        @media (max-width: 860px) { .ilm-portals-list { grid-template-columns: repeat(2, 1fr); } }
        @media (max-width: 500px) { .ilm-portals-list { grid-template-columns: 1fr; } }

        .ilm-portal-row {
          background: #fff; border: 1.5px solid #dfdacd; border-radius: 12px;
          padding: 2rem 1.5rem; cursor: pointer; position: relative; overflow: hidden;
          transition: border-color 0.18s, transform 0.18s, box-shadow 0.18s;
          display: flex; flex-direction: column; align-items: center; text-align: center; gap: 0.5rem;
        }
        .ilm-portal-row:hover { 
          border-color: #506e4d; 
          transform: translateY(-4px);
          box-shadow: 0 12px 30px -8px rgba(0,0,0,0.08);
        }
        .ilm-portal-row.blue:hover { border-color: #1a3566; }
        .ilm-portal-row.amber:hover { border-color: #c06d48; }
        .ilm-portal-row.red:hover { border-color: #a03030; }

        .ilm-portal-icon {
          width: 56px; height: 56px; border-radius: 14px;
          display: flex; align-items: center; justify-content: center; flex-shrink: 0;
          margin-bottom: 0.5rem;
        }
        .ilm-portal-icon.green { background: #f0ede4; color: #506e4d; }
        .ilm-portal-icon.blue  { background: #e8edf8; color: #1a3566; }
        .ilm-portal-icon.amber { background: #faf7f0; color: #c06d48; }
        .ilm-portal-icon.red   { background: #fce8e8; color: #a03030; }

        .ilm-portal-content { flex: 1; display: flex; flex-direction: column; }
        .ilm-portal-row h3 { font-size: 16px; font-weight: 700; color: #2b352a; margin-bottom: 0.5rem; letter-spacing: -0.01em; }
        .ilm-portal-row p  { font-size: 13px; color: #5a6557; line-height: 1.5; margin: 0; flex: 1; }

        .ilm-portal-action {
          display: flex; align-items: center; justify-content: center;
          width: 32px; height: 32px; border-radius: 50%;
          background: #f7f5ef; color: #7b8878; flex-shrink: 0;
          transition: background 0.18s, color 0.18s;
          margin-top: 1rem;
        }
        .ilm-portal-row:hover .ilm-portal-action {
          background: #506e4d; color: #fff;
        }
        .ilm-portal-row.blue:hover .ilm-portal-action { background: #1a3566; }
        .ilm-portal-row.amber:hover .ilm-portal-action { background: #c06d48; }
        .ilm-portal-row.red:hover .ilm-portal-action { background: #a03030; }

        /* ── STATS BAND ── */
        .ilm-stats { background: #2b352a; padding: 3rem 2rem; border-top: 1px solid #dfdacd; border-bottom: 1px solid #dfdacd; }
        .ilm-stats-grid {
          max-width: 920px; margin: 0 auto;
          display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; text-align: center;
        }
        @media (max-width: 600px) { .ilm-stats-grid { grid-template-columns: 1fr 1fr; gap: 1.5rem; } }
        .ilm-stat-val  { font-size: clamp(26px, 4vw, 38px); font-weight: 700; color: #c06d48; letter-spacing: -0.02em; line-height: 1.1; display: block; }
        .ilm-stat-lbl  { font-size: 13px; color: #fff; margin-top: 4px; display: block; font-weight: 500; }
        .ilm-stat-sub  { font-size: 11px; color: #8fa08c; display: block; margin-top: 2px; }

        /* ── FEATURES ── */
        .ilm-features-bg { background: #fff; }
        .ilm-features-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.25rem; }
        @media (max-width: 600px) { .ilm-features-grid { grid-template-columns: 1fr; } }

        .ilm-feature-cell {
          padding: 1.75rem; background: #f7f5ef;
          border: 1px solid #dfdacd; border-radius: 12px;
        }
        .ilm-feature-meta  { display: flex; align-items: center; gap: 8px; margin-bottom: 0.75rem; }
        .ilm-feature-pip   {
          width: 30px; height: 30px; border-radius: 7px;
          display: flex; align-items: center; justify-content: center; flex-shrink: 0;
        }
        .ilm-feature-num   { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: #506e4d; font-weight: 600; }
        .ilm-feature-cat   { font-size: 10px; letter-spacing: 0.1; text-transform: uppercase; color: #7b8878; margin-left: 4px; }
        .ilm-feature-cell h4 { font-size: 15px; font-weight: 700; color: #2b352a; margin-bottom: 0.4rem; letter-spacing: -0.01em; }
        .ilm-feature-cell p  { font-size: 13px; color: #5a6557; line-height: 1.65; }

        /* ── TESTIMONIAL ── */
        .ilm-testimony-bg  { background: #f7f5ef; padding: 4rem 2rem; text-align: center; }
        .ilm-testimony-card {
          max-width: 640px; margin: 0 auto; background: #fff;
          border: 1px solid #dfdacd; border-radius: 14px; padding: 2.5rem 2rem;
        }
        .ilm-stars  { color: #c06d48; font-size: 16px; letter-spacing: 3px; margin-bottom: 1.25rem; }
        .ilm-quote  { font-size: 16px; color: #2b352a; line-height: 1.75; font-style: italic; margin-bottom: 1.5rem; }
        .ilm-quote::before { content: '\\201C'; font-size: 28px; color: #dfdacd; line-height: 0; vertical-align: -0.5rem; margin-right: 4px; }
        .ilm-t-meta  { display: flex; align-items: center; justify-content: center; gap: 12px; }
        .ilm-t-avatar { width: 40px; height: 40px; border-radius: 50%; object-fit: cover; border: 2px solid #dfdacd; }
        .ilm-t-name   { font-size: 13px; font-weight: 600; color: #2b352a; text-align: left; }
        .ilm-t-role   { font-size: 12px; color: #7b8878; }

        /* ── FAQ ── */
        .ilm-faq-bg  { background: #fff; padding: 4rem 2rem; }
        .ilm-faq-row {
          border-bottom: 1px solid #dfdacd; padding: 1.1rem 0; cursor: pointer;
        }
        .ilm-faq-q {
          display: flex; align-items: center; justify-content: space-between; gap: 1rem;
        }
        .ilm-faq-q span { font-size: 14px; font-weight: 500; color: #2b352a; line-height: 1.5; }
        .ilm-faq-chevron {
          flex-shrink: 0; transition: transform 0.2s; color: #7b8878;
        }
        .ilm-faq-row.open .ilm-faq-chevron { transform: rotate(180deg); }
        .ilm-faq-a {
          font-size: 13.5px; color: #675a70; line-height: 1.7;
          padding-top: 0; max-height: 0; overflow: hidden;
          transition: max-height 0.25s ease, padding-top 0.2s;
        }
        .ilm-faq-row.open .ilm-faq-a { max-height: 200px; padding-top: 0.75rem; }

        /* ── FAQ end ── */

        /* ── CTA BOTTOM ── */
        .ilm-cta-bottom { background: #506e4d; padding: 4.5rem 2rem; text-align: center; }
        .ilm-cta-bottom h2 { font-size: clamp(22px, 3vw, 30px); font-weight: 700; color: #fff; margin-bottom: 0.75rem; letter-spacing: -0.015em; }
        .ilm-cta-bottom p  { font-size: 15px; color: #f0ede4; max-width: 500px; margin: 0 auto 2rem; line-height: 1.7; }
        .ilm-cta-bottom-btns { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }
        .ilm-btn-gold {
          background: #fff; color: #506e4d; padding: 13px 28px; border-radius: 8px;
          font-size: 14px; font-weight: 600; border: none; cursor: pointer; letter-spacing: 0.01em;
          transition: background 0.15s;
        }
        .ilm-btn-gold:hover { background: #f0ede4; }
        .ilm-btn-outline-light {
          background: transparent; color: #f0ede4; padding: 13px 28px; border-radius: 8px;
          font-size: 14px; font-weight: 500; border: 1.5px solid rgba(255,255,255,0.4); cursor: pointer;
          letter-spacing: 0.01em; transition: background 0.15s;
        }
        .ilm-btn-outline-light:hover { background: rgba(255,255,255,0.1); }

        /* ── FOOTER ── */
        .ilm-footer { background: #2b352a; padding: 3rem 2rem 1.5rem; }
        .ilm-footer-top {
          display: grid; grid-template-columns: 2fr 1fr; gap: 2rem;
          max-width: 920px; margin: 0 auto 2rem; padding-bottom: 2rem;
          border-bottom: 1px solid #3d4a3c;
        }
        @media (max-width: 640px) { .ilm-footer-top { grid-template-columns: 1fr; } }
        .ilm-footer-brand     { font-size: 16px; font-weight: 700; color: #fff; letter-spacing: 0.07em; margin-bottom: 0.6rem; }
        .ilm-footer-about     { font-size: 13px; line-height: 1.7; color: #8fa08c; max-width: 280px; }
        .ilm-footer-col-title { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: #506e4d; font-weight: 600; display: block; margin-bottom: 0.75rem; }
        .ilm-footer-col a, .ilm-footer-col span { display: block; font-size: 13px; color: #8fa08c; text-decoration: none; margin-bottom: 5px; line-height: 1.6; }
        .ilm-footer-col a:hover { color: #506e4d; }
        .ilm-footer-bottom { max-width: 920px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 8px; }
        .ilm-footer-reg     { font-size: 11px; color: #506e4d; }
        .ilm-footer-copy    { font-size: 12px; color: #7b8878; }
      `}</style>

      <div className="ilm-page">

        {/* ── NAV ── */}
        <header className="ilm-nav">
          <div className="ilm-nav-logo">
            <img src="/ilmee_logo.png" alt="ILMEE Logo" className="ilm-logo-img" style={{ width: '36px', height: '36px', borderRadius: '8px', objectFit: 'contain' }} />
            <div>
              <span className="ilm-brand-name">ILMEE</span>
              <span className="ilm-brand-tag">Educational Portals</span>
            </div>
          </div>
          <ul className="ilm-nav-links">
            <li><a href="#portals">Portals</a></li>
            <li><a href="#stats">Our Impact</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#faqs">FAQs</a></li>
          </ul>
          <div className="ilm-nav-badge">
            <Shield size={12} />
            UK Safeguarding Aligned
          </div>
        </header>



        {/* ── HERO ── */}
        <section className="ilm-hero">
          <div className="ilm-eyebrow">
            <HeartHandshake size={12} />
            Trusted by 25,000+ families across the UK &amp; Egypt
          </div>
          <h1>
            The <span className="h1-accent">modern curriculum</span> platform{' '}
            for <span className="h1-underline">every learner</span>
          </h1>
          <p className="ilm-hero-sub">
            ILMEE brings homeschooling and professional tuition together in one secure,
            Ofsted-aligned portal — with AI-powered support and built-in safeguarding.
            Available in the UK and Egypt.
          </p>
          <div className="ilm-hero-ctas">
            <a href="#portals" className="ilm-btn-primary">
              Explore portals <ArrowRight size={14} />
            </a>
            <a href="#features" className="ilm-btn-secondary">
              Learn more
            </a>
          </div>
        </section>



        {/* ── ROLES ── */}
        <section id="portals" className="ilm-section ilm-portals-bg">
          <div className="ilm-container">
            <div className="ilm-section-hdr" style={{ textAlign: 'center', maxWidth: '600px', margin: '0 auto 2.5rem' }}>
              <p className="ilm-section-label">LSA Portal Access</p>
              <h2 className="ilm-section-title">Select your role to continue</h2>
              <p className="ilm-section-desc" style={{ margin: '0 auto' }}>
                Log in to access your tailored dashboard for the Tuition portal.
              </p>
            </div>
            
            <div className="ilm-portals-list">
              {/* School */}
              <div className="ilm-portal-row green" onClick={() => handleSelectPortal('/login-school')}>
                <div className="ilm-portal-icon green"><School size={24} /></div>
                <div className="ilm-portal-content">
                  <h3>School Administration</h3>
                  <p>Manage your institution's tuition schedules, oversee teachers, and track overall student progress.</p>
                </div>
                <div className="ilm-portal-action"><ArrowRight size={16} /></div>
              </div>

              {/* Teacher */}
              <div className="ilm-portal-row amber" onClick={() => handleSelectPortal('/login-teacher')}>
                <div className="ilm-portal-icon amber"><BookOpen size={24} /></div>
                <div className="ilm-portal-content">
                  <h3>Teacher Portal</h3>
                  <p>Access your teaching schedule, upload lesson materials, and provide feedback directly to students.</p>
                </div>
                <div className="ilm-portal-action"><ArrowRight size={16} /></div>
              </div>

              {/* Student */}
              <div className="ilm-portal-row blue" onClick={() => handleSelectPortal('/login-student')}>
                <div className="ilm-portal-icon blue"><BarChart size={24} /></div>
                <div className="ilm-portal-content">
                  <h3>Student Portal</h3>
                  <p>Join live tuition sessions, track your assignments, and review feedback from your teachers.</p>
                </div>
                <div className="ilm-portal-action"><ArrowRight size={16} /></div>
              </div>

              {/* Safeguard */}
              <div className="ilm-portal-row red" onClick={() => handleSelectPortal('/login-safeguard')}>
                <div className="ilm-portal-icon red"><Shield size={24} /></div>
                <div className="ilm-portal-content">
                  <h3>Safeguarding Portal</h3>
                  <p>Monitor daily wellbeing logs and oversee immediate concern escalations securely.</p>
                </div>
                <div className="ilm-portal-action"><ArrowRight size={16} /></div>
              </div>
            </div>
          </div>
        </section>

        {/* ── STATS ── */}
        <section id="stats" className="ilm-stats">
          <div className="ilm-stats-grid">
            {stats.map((s, i) => (
              <div key={i}>
                <span className="ilm-stat-val">{s.value}</span>
                <span className="ilm-stat-lbl">{s.label}</span>
                <span className="ilm-stat-sub">{s.sub}</span>
              </div>
            ))}
          </div>
        </section>

        {/* ── FEATURES ── */}
        <section id="features" className="ilm-section ilm-features-bg">
          <div className="ilm-container">
            <div className="ilm-section-hdr">
              <p className="ilm-section-label">Platform capabilities</p>
              <h2 className="ilm-section-title">Everything you need in one place</h2>
              <p className="ilm-section-desc">
                Built for families, compliance officers, and educators who need a platform
                that keeps pace with real-world demands in the UK and Egypt.
              </p>
            </div>
            <div className="ilm-features-grid">
              {features.map((f) => {
                const c = featureColorMap[f.color];
                return (
                  <div key={f.number} className="ilm-feature-cell">
                    <div className="ilm-feature-meta">
                      <div className="ilm-feature-pip" style={{ background: c.bg, color: c.icon }}>
                        {f.icon}
                      </div>
                      <span className="ilm-feature-num">{f.number}</span>
                      <span className="ilm-feature-cat">· {f.category}</span>
                    </div>
                    <h4>{f.title}</h4>
                    <p>{f.description}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── TESTIMONIAL ── */}
        <section className="ilm-testimony-bg">
          <div className="ilm-testimony-card">
            <div className="ilm-stars">★★★★★</div>
            <p className="ilm-quote">
              The ILMEE homeschooling dashboard has saved our family countless hours.
              We have instant access to lessons, can track progress in real-time, and
              download complete reports required by our local authority.
            </p>
            <div className="ilm-t-meta">
              <img
                src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=80"
                alt="Sarah Jenkins"
                className="ilm-t-avatar"
              />
              <div>
                <p className="ilm-t-name">Sarah Jenkins</p>
                <p className="ilm-t-role">Parent · Year 4 &amp; Year 7 · Birmingham</p>
              </div>
            </div>
          </div>
        </section>

        {/* ── FAQ ── */}
        <section id="faqs" className="ilm-faq-bg">
          <div className="ilm-container" style={{ maxWidth: 720 }}>
            <div className="ilm-section-hdr">
              <p className="ilm-section-label">Questions</p>
              <h2 className="ilm-section-title">Frequently asked</h2>
            </div>
            {faqs.map((faq, i) => (
              <div
                key={i}
                className={`ilm-faq-row${activeFAQ === i ? ' open' : ''}`}
                onClick={() => toggleFAQ(i)}
              >
                <div className="ilm-faq-q">
                  <span>{faq.question}</span>
                  <ChevronDown size={16} className="ilm-faq-chevron" />
                </div>
                <div className="ilm-faq-a">{faq.answer}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ── CTA BOTTOM ── */}
        <section className="ilm-cta-bottom">
          <h2>Ready to transform your educational experience?</h2>
          <p>
            Join thousands of schools, teachers, and students across the UK and Egypt
            delivering high-quality, compliant tuition through ILMEE.
          </p>
          <div className="ilm-cta-bottom-btns">
            <button className="ilm-btn-gold" onClick={() => handleSelectPortal('/login-school')}>
              School login
            </button>
            <button className="ilm-btn-outline-light" onClick={() => handleSelectPortal('/register-school')}>
              Register a school
            </button>
          </div>
        </section>

        {/* ── FOOTER ── */}
        <footer className="ilm-footer">
          <div className="ilm-footer-top">
            <div>
              <p className="ilm-footer-brand">ILMEE</p>
              <p className="ilm-footer-about">
                Structured learning, automated parent oversight, and pupil safeguarding
                under the British National Curriculum framework — available in the UK and Egypt.
              </p>
            </div>
            <div className="ilm-footer-col">
              <span className="ilm-footer-col-title">Portals</span>
              <a href="/login-school" onClick={(e) => { e.preventDefault(); handleSelectPortal('/login-school'); }}>School Portal</a>
              <a href="/login-teacher" onClick={(e) => { e.preventDefault(); handleSelectPortal('/login-teacher'); }}>Teacher Portal</a>
              <a href="/login-student" onClick={(e) => { e.preventDefault(); handleSelectPortal('/login-student'); }}>Student Portal</a>
              <a href="/login-safeguard" onClick={(e) => { e.preventDefault(); handleSelectPortal('/login-safeguard'); }}>Safeguard Portal</a>
            </div>

          </div>
          <div className="ilm-footer-bottom">
            <p className="ilm-footer-reg">Registered UK Organisation · DfE Aligned · Safeguarding Framework Compliant</p>
            <p className="ilm-footer-copy">&copy; {new Date().getFullYear()} ILMEE Education. All rights reserved.</p>
          </div>
        </footer>

      </div>
    </>
  );
}